Repository Tesis-Proyeccion-Social-UesOcc/proyeccion-social-ws-api, pull requests merged in 2021-04, with the labels that each got.

#34 Fix bug in EstudianteServiceImpl
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/EstadoRequerimientoEstudianteMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/EstadoRequerimientoEstudianteDTO.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/EstudianteServiceImpl.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/EstudianteServiceImplTest.java
Labels: bugfix

#37 Feature/new endpoint estudiante
  pom.xml
  src/main/java/ues/occ/proyeccion/social/ws/app/controller/EstudianteController.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/ProyectoCreationDTO.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/ProyectoRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/PersonalServiceImpl.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/ProyectoService.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImpl.java
  src/test/java/ues/occ/proyeccion/social/ws/app/controller/EstudianteControllerTest.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImplTest.java
Labels: enhancement

#36 Update template in document controller
  .gitignore
  src/main/java/ues/occ/proyeccion/social/ws/app/controller/DocumentoPlantillaController.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/DocumentoPlantilla.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/DocumentoService.java
Labels: enhancement

#38 Feature/refactor entity relatioships
  src/main/java/ues/occ/proyeccion/social/ws/app/controller/EstudianteController.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/Certificado.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/EstadoRequerimientoEstudiante.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/EstadoRequerimientoEstudiantePK.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/Estudiante.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/Proyecto.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/ProyectoEstudiante.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/ProyectoEstudiantePK.java
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/CertificadoMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/ProyectoMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/SimpleDocumentMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/CertificadoCreationDTO.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/SimpleDocumentDTO.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/CertificadoRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/DocumentoRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/EstadoRequerimientoEstudianteRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/ProyectoEstudianteRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/ProyectoRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/CertificadoServiceImpl.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/EstadoRequerimientoEstudianteService.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/EstadoRequerimientoEstudianteServiceImpl.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/ProyectoService.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImpl.java
  src/main/resources/application-dev.properties
  src/test/java/ues/occ/proyeccion/social/ws/app/controller/CertificadoControllerTest.java
  src/test/java/ues/occ/proyeccion/social/ws/app/controller/EstudianteControllerTest.java
  src/test/java/ues/occ/proyeccion/social/ws/app/entities/SpringDataIT.java
  src/test/java/ues/occ/proyeccion/social/ws/app/repository/CertificadoRepositoryIT.java
  src/test/java/ues/occ/proyeccion/social/ws/app/repository/DocumentoRepositoryIT.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/CertificadoServiceTest.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/EstadoRequerimientoEstudianteServiceImplTest.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImplTest.java
Labels: breaking change, enhancement

#39 Add idRequerimiento in SimpleDocumentDTO
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/SimpleDocumentMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/SimpleDocumentDTO.java
  src/test/java/ues/occ/proyeccion/social/ws/app/controller/EstudianteControllerTest.java
Labels: enhancement

#40 Feature/proceso resources
  src/main/java/ues/occ/proyeccion/social/ws/app/controller/EstudianteController.java
  src/main/java/ues/occ/proyeccion/social/ws/app/controller/ProcesoController.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/Proceso.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/ServiceResponse.java
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/ProcesoMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/ProcesoDTO.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/ProcesoRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/CertificadoServiceImpl.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/DepartamentoServiceimpl.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/DocumentoPlantilla.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/EstudianteServiceImpl.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/PersonalServiceImpl.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/ProcesoService.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/ProcesoServiceImpl.java
  src/main/resources/application-prod.properties
  src/test/java/ues/occ/proyeccion/social/ws/app/controller/ProcesoControllerTest.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/ProcesoServiceImplTest.java
Labels: enhancement

#44 Bugfix/requerimiento creation in project creation
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/EstadoRequerimientoEstudiante.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/EstadoRequerimientoEstudiantePK.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/Proceso.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/ProyectoEstudiante.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/Requerimiento.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/RequerimientoRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/projections/RequerimientoIdView.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImpl.java
  src/main/resources/application-test.properties
  src/test/java/ues/occ/proyeccion/social/ws/app/repository/DocumentoRepositoryIT.java
  src/test/java/ues/occ/proyeccion/social/ws/app/repository/ProyectoRepositoryIT.java
  src/test/java/ues/occ/proyeccion/social/ws/app/repository/RequerimientoRepositoryIT.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceIT.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImplTest.java
Labels: bugfix, enhancement

#45 Feature/proyecto estudiante id in simple document dto
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/SimpleDocumentMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/SimpleDocumentDTO.java
  src/test/java/ues/occ/proyeccion/social/ws/app/controller/EstudianteControllerTest.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImplTest.java
Labels: enhancement

#48 Feature/filter data by active flag
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/EstadoRequerimientoEstudiante.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/ProyectoEstudiante.java
  src/main/java/ues/occ/proyeccion/social/ws/app/dao/Requerimiento.java
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/EstudianteMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/ProyectoMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/mappers/SimpleDocumentMapper.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/EmbeddedStudentDTO.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/PendingProjectDTO.java
  src/main/java/ues/occ/proyeccion/social/ws/app/model/ProyectoCreationDTO.java
  src/main/java/ues/occ/proyeccion/social/ws/app/repository/DocumentoRepository.java
  src/main/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImpl.java
  src/test/java/ues/occ/proyeccion/social/ws/app/controller/ProyectoControllerTest.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceIT.java
  src/test/java/ues/occ/proyeccion/social/ws/app/service/ProyectoServiceImplTest.java
Labels: enhancement
